#!/usr/bin/env python3
"""根据 deploy.env 与定制仓 projects/registry.yaml 生成 workspace.yaml。"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

try:
    import yaml
except ImportError as exc:  # pragma: no cover
    raise SystemExit("需要 PyYAML: pip install pyyaml") from exc

ROOT = Path(__file__).resolve().parents[3]
DEFAULT_REGISTRY = "projects/registry.yaml"
PRO_APPS = ["kuaiai", "kuaireport", "kuaiiot"]


def _relpath(from_root: Path, target: Path) -> str:
    try:
        return os.path.relpath(str(target.resolve()), str(from_root.resolve())).replace("\\", "/")
    except ValueError:
        return str(target)


def _load_registry(custom_repo: Path) -> dict:
    path = custom_repo / DEFAULT_REGISTRY
    if not path.is_file():
        raise SystemExit(f"定制仓缺少注册表: {path}")
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    projects = data.get("projects")
    if not isinstance(projects, dict) or not projects:
        raise SystemExit(f"注册表无 projects: {path}")
    return projects


def _resolve_custom_bindings(custom_repo: Path, projects_csv: str) -> list[dict]:
    registry = _load_registry(custom_repo)
    names = [p.strip() for p in (projects_csv or "").split(",") if p.strip()]
    if not names:
        raise SystemExit(
            "CUSTOM_ENABLED=1 时必须设置 CUSTOM_PROJECTS（逗号分隔项目 id，见定制仓 projects/registry.yaml）"
        )
    bindings: list[dict] = []
    for name in names:
        entry = registry.get(name)
        if not isinstance(entry, dict):
            known = ", ".join(sorted(registry.keys()))
            raise SystemExit(f"未知定制项目 '{name}'，可选: {known}")
        apps = entry.get("apps")
        if isinstance(apps, str):
            backend = frontend = apps
        elif isinstance(apps, dict):
            backend = str(apps.get("backend") or name).strip()
            frontend = str(apps.get("frontend") or backend).strip()
        else:
            backend = frontend = name
        bindings.append({"backend": backend, "frontend": frontend, "project": name})
    return bindings


def build_workspace(
    *,
    mode: str,
    pro_enabled: bool,
    custom_enabled: bool,
    pro_repo: Path,
    custom_repo: Path,
    custom_projects: str,
) -> dict:
    plugins: list[dict] = []
    if pro_enabled:
        plugins.append(
            {
                "repo": _relpath(ROOT, pro_repo),
                "apps": list(PRO_APPS),
            }
        )
    if custom_enabled:
        bindings = _resolve_custom_bindings(custom_repo, custom_projects)
        plugin: dict = {"repo": _relpath(ROOT, custom_repo), "app_bindings": bindings}
        plugins.append(plugin)
    if not plugins:
        raise SystemExit("PRO_ENABLED / CUSTOM_ENABLED 均为未启用，无法生成 workspace.yaml")
    return {"mode": mode, "plugins": plugins}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, help="workspace.yaml 输出路径")
    parser.add_argument("--mode", default=os.environ.get("WORKSPACE_COMPOSE_MODE", "copy"))
    parser.add_argument("--pro-enabled", default=os.environ.get("PRO_ENABLED", "0"))
    parser.add_argument("--custom-enabled", default=os.environ.get("CUSTOM_ENABLED", "0"))
    parser.add_argument("--pro-repo", default=os.environ.get("PRO_REPO_PATH", ""))
    parser.add_argument("--custom-repo", default=os.environ.get("CUSTOM_REPO_PATH", ""))
    parser.add_argument("--custom-projects", default=os.environ.get("CUSTOM_PROJECTS", ""))
    args = parser.parse_args()

    pro_en = str(args.pro_enabled).strip() == "1"
    custom_en = str(args.custom_enabled).strip() == "1"
    pro_repo = Path(args.pro_repo) if args.pro_repo else (ROOT.parent / "kuaigeyun-pro")
    custom_repo = Path(args.custom_repo) if args.custom_repo else (ROOT.parent / "kuaigeyun-custom")

    doc = build_workspace(
        mode=str(args.mode or "copy"),
        pro_enabled=pro_en,
        custom_enabled=custom_en,
        pro_repo=pro_repo,
        custom_repo=custom_repo,
        custom_projects=str(args.custom_projects or ""),
    )
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    header = "# generated by fast-deploy — do not commit secrets\n"
    out.write_text(header + yaml.safe_dump(doc, allow_unicode=True, sort_keys=False), encoding="utf-8")
    print(f"Wrote {out} ({len(doc.get('plugins') or [])} plugins)")


if __name__ == "__main__":
    main()
