#!/usr/bin/env python3
"""从 manifest 已更新的 /apps/{dedicated}/ 菜单 path 重建 routes.host-mirror.generated.tsx"""

from __future__ import annotations

import importlib.util
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src" / "apps"
BACKEND = ROOT.parent / "riveredge-backend" / "src" / "apps"

spec = importlib.util.spec_from_file_location(
    "mirror", ROOT / "scripts" / "mirror_dedicated_host_pages.py"
)
mirror = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(mirror)


def load_manifest(app_code: str) -> dict:
    return json.loads((BACKEND / app_code.replace("-", "_") / "manifest.json").read_text("utf-8"))


def iter_paths(node) -> list[str]:
    out: list[str] = []
    if isinstance(node, dict):
        p = node.get("path")
        if isinstance(p, str):
            out.append(p.split("?")[0].rstrip("/"))
        for ch in node.get("children") or []:
            out.extend(iter_paths(ch))
    elif isinstance(node, list):
        for x in node:
            out.extend(iter_paths(x))
    return out


def dedicated_rest_to_host_page(dedicated: str, rest: str) -> tuple[str, str, str] | None:
    prefix = f"/apps/{dedicated}/"
    if not rest.startswith(prefix):
        return None
    dr = rest[len(prefix) :]
    if dr.startswith("master-data/"):
        host_app = "master-data"
        page_dir = mirror.resolve_host_page_dir(host_app, dr)
    elif dr.startswith("hr/") or dr.startswith("approval/") or dr.startswith("collaboration/") or dr.startswith("compliance/") or dr.startswith("assets/"):
        host_app = "kuaioa"
        page_dir = mirror.resolve_host_page_dir(host_app, dr)
    else:
        kuaiplm_first = dr.split("/")[0]
        kuaiplm_set = {
            "dashboard", "pending-inbox", "rd-projects", "rd-deliverables", "change-management",
            "knowledge-base", "bom-collaborations", "product-firmwares", "production-files",
            "lab-requests", "lab-board", "lab-judgment-rules", "annual-lab-plans", "trial-flows",
            "sample-process-applications", "material-reviews", "mold-sample-orders", "prototype-build-sheets",
        }
        if kuaiplm_first in kuaiplm_set or dr.startswith("phase2/"):
            host_app = "kuaiplm"
        else:
            host_app = "kuaizhizao"
        page_dir = mirror.resolve_host_page_dir(host_app, dr)
    rel = page_dir.replace("pages/", "", 1)
    if rel.endswith(".tsx"):
        rel = rel[: -len(".tsx")]
    return dr, host_app, rel


def is_host_mirror_menu_path(dedicated: str, dedicated_rest: str) -> bool:
    if dedicated == "funide-oa":
        return dedicated_rest not in ("project-proposals", "workbench")
    if dedicated == "haoligo":
        return dedicated_rest.startswith("master-data/") or dedicated_rest.startswith("hr/")
    return False


def main() -> int:
    dedicated = sys.argv[1]
    paths = sorted(set(iter_paths(load_manifest(dedicated).get("menu_config") or {})))
    route_map: dict[str, str] = {}
    skip = {f"/apps/{dedicated}"}
    for p in paths:
        if p in skip or not p.startswith(f"/apps/{dedicated}/"):
            continue
        dr = p[len(f"/apps/{dedicated}/") :]
        if not is_host_mirror_menu_path(dedicated, dr):
            continue
        resolved = dedicated_rest_to_host_page(dedicated, p)
        if not resolved:
            continue
        dr, host_app, rel = resolved
        route_map[dr] = f"./pages/{host_app}/{rel}"

    for (ha, key), extras in mirror.ROUTE_EXTRA.get(dedicated, {}).items():
        for extra_route, extra_page in extras:
            rel = extra_page.replace("pages/", "", 1)
            if rel.endswith(".tsx"):
                rel = rel[: -len(".tsx")]
            route_map[extra_route] = f"./pages/{ha}/{rel}"

    lines = [
        "/** AUTO-GENERATED by scripts/regenerate_dedicated_mirror_routes.py — do not hand-edit */",
        "import React, { Suspense, lazy } from 'react';",
        "import { Route } from 'react-router-dom';",
        "import PageSkeleton from '../../components/page-skeleton';",
        "",
        "const withPageSuspense = (C: React.LazyExoticComponent<React.ComponentType>) => (",
        "  <Suspense fallback={<PageSkeleton />}><C /></Suspense>",
        ");",
        "",
    ]
    for route_path, import_path in sorted(route_map.items()):
        var = re.sub(r"[^a-zA-Z0-9]", "_", route_path) + "Page"
        lines.append(f"const {var} = lazy(() => import('{import_path}'));")
    lines += ["", "export const dedicatedHostMirrorRoutes = (", "  <>"]
    for route_path in sorted(route_map.keys()):
        var = re.sub(r"[^a-zA-Z0-9]", "_", route_path) + "Page"
        lines.append(f'    <Route path="{route_path}" element={{withPageSuspense({var})}} />')
    lines += ["  </>", ");", ""]
    out = SRC / dedicated / "routes.host-mirror.generated.tsx"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"routes: {len(route_map)} for {dedicated}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
