"""供方年度现场审核条款（真源 质量部/供方年度评价表.xls 审核项目，0-3 分）。"""

from __future__ import annotations

from typing import Any

ELECTRONICS_SUPPLIER_EVAL_ANNUAL_ONSITE_CLAUSES: list[dict[str, Any]] = [
    {"line_no": 1, "clause_code": "A01", "clause_name": '技术负责人的设计经验可否达到我司的要求？', "weight": 1, "max_score": 3, "remarks": '研发/设计能力'},
    {"line_no": 2, "clause_code": "A02", "clause_name": '研发周期可否达到我司要求？', "weight": 1, "max_score": 3, "remarks": '研发/设计能力'},
    {"line_no": 3, "clause_code": "A03", "clause_name": '有否产品的技术标准和试验标准，该标准可否满足我司的产品要求？', "weight": 1, "max_score": 3, "remarks": '研发/设计流程管理'},
    {"line_no": 4, "clause_code": "A04", "clause_name": '产品开发阶段的试验（包括试产）记录是否完整？', "weight": 1, "max_score": 3, "remarks": '研发/设计流程管理'},
    {"line_no": 5, "clause_code": "A05", "clause_name": '有否经过审批的合格原材料供应商的清单？', "weight": 1, "max_score": 3, "remarks": '原材料控制/供应商管理'},
    {"line_no": 6, "clause_code": "A06", "clause_name": '有否对供应商制定绩效评审细则并定期进行评审？', "weight": 1, "max_score": 3, "remarks": '原材料控制/供应商管理'},
    {"line_no": 7, "clause_code": "A07", "clause_name": '有否对供应商制定年度审查计划并定期审查？', "weight": 1, "max_score": 3, "remarks": '原材料控制/供应商管理'},
    {"line_no": 8, "clause_code": "A08", "clause_name": '有否对供应商纠正措施的跟踪与验证？且是否闭环管理？', "weight": 1, "max_score": 3, "remarks": '原材料控制/供应商管理'},
    {"line_no": 9, "clause_code": "A09", "clause_name": '有否和供应商签订技术质量协议书？', "weight": 1, "max_score": 3, "remarks": '原材料控制/供应商管理'},
    {"line_no": 10, "clause_code": "A10", "clause_name": '有否进货检验程序与明确的抽样计划及方案？', "weight": 1, "max_score": 3, "remarks": '原材料控制/IQC管理'},
    {"line_no": 11, "clause_code": "A11", "clause_name": '是否对关键原材料制订了相应的检验规范？', "weight": 1, "max_score": 3, "remarks": '原材料控制/IQC管理'},
    {"line_no": 12, "clause_code": "A12", "clause_name": '检验规范有否列出对物料关键参数的检查及具备相应的工具？', "weight": 1, "max_score": 3, "remarks": '原材料控制/IQC管理'},
    {"line_no": 13, "clause_code": "A13", "clause_name": '检查记录是否列明供应商名称、来料日期、批号、检验员、检查及处理结果，以及相关人员的审批？', "weight": 1, "max_score": 3, "remarks": '原材料控制/IQC管理'},
    {"line_no": 14, "clause_code": "A14", "clause_name": '检验人员的上岗证明及考核记录是否符合岗位要求？', "weight": 1, "max_score": 3, "remarks": '原材料控制/IQC管理'},
    {"line_no": 15, "clause_code": "A15", "clause_name": '来料区物料有否明确的状态标识？', "weight": 1, "max_score": 3, "remarks": '原材料控制/IQC管理'},
    {"line_no": 16, "clause_code": "A16", "clause_name": '有否制订各类产品的QC工程图？', "weight": 1, "max_score": 3, "remarks": '生产过程控制/文件控制'},
    {"line_no": 17, "clause_code": "A17", "clause_name": '作业指导书是否与作业内容相符？', "weight": 1, "max_score": 3, "remarks": '生产过程控制/文件控制'},
    {"line_no": 18, "clause_code": "A18", "clause_name": '作业现场的各种产品(成品/半成品、合格品/不合格品、不同部品等)有适当的摆放位置、区隔方式及清楚标示，以避免混料或误用', "weight": 1, "max_score": 3, "remarks": '生产过程控制/现场管理'},
    {"line_no": 19, "clause_code": "A19", "clause_name": '机台或量测设备有清楚标示校正日期、周期、下次校验时间，以及使用状态标示', "weight": 1, "max_score": 3, "remarks": '生产过程控制/现场管理'},
    {"line_no": 20, "clause_code": "A20", "clause_name": '作业员与检验员有依照生产作业的操作(SOP)、检查及测试(IS/SIP)执行及纪录', "weight": 1, "max_score": 3, "remarks": '生产过程控制/现场管理'},
    {"line_no": 21, "clause_code": "A21", "clause_name": '生产设备及制造作业在符合生产的条件下(点检纪录)进行生产，以确保产品质量符合要求', "weight": 1, "max_score": 3, "remarks": '生产过程控制/现场管理'},
    {"line_no": 22, "clause_code": "A22", "clause_name": '对于影响机台生产绩效的重要项目及参数调整(含软件)，能予以控管并有纪录', "weight": 1, "max_score": 3, "remarks": '生产过程控制/现场管理'},
    {"line_no": 23, "clause_code": "A23", "clause_name": '对制程异常，有适当的进行调查、分析、矫正与改善，使制程回复稳定状态并有纪录保存', "weight": 1, "max_score": 3, "remarks": '生产过程控制/现场管理'},
    {"line_no": 24, "clause_code": "A24", "clause_name": '制程有实时监控系统及停线或异常管控机制，以避免异常持续恶化', "weight": 1, "max_score": 3, "remarks": '生产过程控制/现场管理'},
    {"line_no": 25, "clause_code": "A25", "clause_name": '在制程中产品发现不良时，有被确实记录在各站生产表单中', "weight": 1, "max_score": 3, "remarks": '生产过程控制/现场管理'},
    {"line_no": 26, "clause_code": "A26", "clause_name": '有制程重工、返修的作业标准，以确保重工品、返修品符合客户需求', "weight": 1, "max_score": 3, "remarks": '生产过程控制/现场管理'},
    {"line_no": 27, "clause_code": "A27", "clause_name": '有书面程序规范不符规格产品审查过程(特采机制)', "weight": 1, "max_score": 3, "remarks": '生产过程控制/现场管理'},
    {"line_no": 28, "clause_code": "A28", "clause_name": '有信息系统提供每批产品的追溯资料，例如：机型、机号、制造日期、作业员、设备及主要原物料等', "weight": 1, "max_score": 3, "remarks": '生产过程控制/现场管理'},
    {"line_no": 29, "clause_code": "A29", "clause_name": '有产品及制程的良率目标，并定期予以检讨、改善', "weight": 1, "max_score": 3, "remarks": '生产过程控制/现场管理'},
    {"line_no": 30, "clause_code": "A30", "clause_name": '生产作业人员与检验人员均有经过适当的培训与上岗证', "weight": 1, "max_score": 3, "remarks": '生产过程控制/现场管理'},
    {"line_no": 31, "clause_code": "A31", "clause_name": '有年度设备预防保养计划，对设备进行日常及定期维护保养，并有维护纪录', "weight": 1, "max_score": 3, "remarks": '生产过程控制/现场管理'},
    {"line_no": 32, "clause_code": "A32", "clause_name": '对于设备异常的维修，有历史纪录，并有证据与资料显示维修后的机台能正常的生产出品质稳定的产品', "weight": 1, "max_score": 3, "remarks": '生产过程控制/现场管理'},
    {"line_no": 33, "clause_code": "A33", "clause_name": '所有设备是否接地？', "weight": 1, "max_score": 3, "remarks": '生产过程控制/现场管理'},
    {"line_no": 34, "clause_code": "A34", "clause_name": '有无使用OK样机、NG样机对设备定期进行校验？', "weight": 1, "max_score": 3, "remarks": '生产过程控制/现场管理'},
    {"line_no": 35, "clause_code": "A35", "clause_name": '过程及出货检查的接收标准和抽样计划', "weight": 1, "max_score": 3, "remarks": '检验、试验/检验控制'},
    {"line_no": 36, "clause_code": "A36", "clause_name": '检验、试验记录是否完整、准确', "weight": 1, "max_score": 3, "remarks": '检验、试验/检验控制'},
    {"line_no": 37, "clause_code": "A37", "clause_name": '对检验、试验不合格批有否有效处理及跟踪', "weight": 1, "max_score": 3, "remarks": '检验、试验/检验控制'},
    {"line_no": 38, "clause_code": "A38", "clause_name": '是否制订年度的管理试验计划', "weight": 1, "max_score": 3, "remarks": '检验、试验/管理试验及可靠性试验'},
    {"line_no": 39, "clause_code": "A39", "clause_name": '有否新品的可靠性试验', "weight": 1, "max_score": 3, "remarks": '检验、试验/管理试验及可靠性试验'},
    {"line_no": 40, "clause_code": "A40", "clause_name": '量产品是否有依管理试验计划进行可靠性月度管理实验', "weight": 1, "max_score": 3, "remarks": '检验、试验/管理试验及可靠性试验'},
    {"line_no": 41, "clause_code": "A41", "clause_name": '对试验不合格的产品是否进行有效追溯和跟踪处理', "weight": 1, "max_score": 3, "remarks": '检验、试验/管理试验及可靠性试验'},
    {"line_no": 42, "clause_code": "A42", "clause_name": '试验人员是否对实验要求及实验操作熟悉，是否有获得试验相关培训，上岗资格可否满足要求', "weight": 1, "max_score": 3, "remarks": '检验、试验/管理试验及可靠性试验'},
    {"line_no": 43, "clause_code": "A43", "clause_name": '有否按FIFO原则对仓库产品进行管理', "weight": 1, "max_score": 3, "remarks": '仓储管理/仓储管理'},
    {"line_no": 44, "clause_code": "A44", "clause_name": '有否对仓储环境进行规定', "weight": 1, "max_score": 3, "remarks": '仓储管理/仓储管理'},
    {"line_no": 45, "clause_code": "A45", "clause_name": '有否超期产品处理流程并按此流程严格执行,且是否闭环管理', "weight": 1, "max_score": 3, "remarks": '仓储管理/仓储管理'},
    {"line_no": 46, "clause_code": "A46", "clause_name": '产品出货记录是否明确记录，可以追溯到具体生产批次和数量？', "weight": 1, "max_score": 3, "remarks": '仓储管理/仓储管理'},
    {"line_no": 47, "clause_code": "A47", "clause_name": '有否对客户满意度的调查（评价标准）及改良措施,且是否闭环管理？', "weight": 1, "max_score": 3, "remarks": '客户、服务管理/客户、服务管理'},
    {"line_no": 48, "clause_code": "A48", "clause_name": '有无完整的客户投诉记录？对客户投诉的回复是否按8D的内容进行分析改善和验证，且是否闭环管理？', "weight": 1, "max_score": 3, "remarks": '客户、服务管理/客户、服务管理'},
    {"line_no": 49, "clause_code": "A49", "clause_name": '是否制定产品质量目标及分解', "weight": 1, "max_score": 3, "remarks": '体系与质量目标/体系的维护'},
    {"line_no": 50, "clause_code": "A50", "clause_name": '针对产品质量目标，是否定期统计分析，并组织持续改善，及组织实施闭环管理', "weight": 1, "max_score": 3, "remarks": '体系与质量目标/体系的维护'},
    {"line_no": 51, "clause_code": "A51", "clause_name": '公司质量管理部门是否属公司最高管理层直管？\n质量管理组织架构和职能是否独立在生产管理之外？具有权威性。', "weight": 1, "max_score": 3, "remarks": '体系与质量目标/体系的维护'},
    {"line_no": 52, "clause_code": "A52", "clause_name": '是否定期组织内部质量管理体系（或环境质量管理体系）审核？', "weight": 1, "max_score": 3, "remarks": '体系与质量目标/体系的维护'},
    {"line_no": 53, "clause_code": "A53", "clause_name": '针对审核的不合格项，是否制定有效的改善措施给予改善并验证？且是否闭环管理？', "weight": 1, "max_score": 3, "remarks": '体系与质量目标/体系的维护'},
    {"line_no": 54, "clause_code": "A54", "clause_name": '是否组织管理评审？对质量管理体系的有效性进行评估以持续改进？', "weight": 1, "max_score": 3, "remarks": '体系与质量目标/体系的维护'},
    {"line_no": 55, "clause_code": "A55", "clause_name": 'QC080000等有害物质管理体系认证情况', "weight": 1, "max_score": 3, "remarks": 'RoHS/环保体系及维护'},
    {"line_no": 56, "clause_code": "A56", "clause_name": 'RoHS管理手册、规范和程序文件', "weight": 1, "max_score": 3, "remarks": 'RoHS/环保体系及维护'},
    {"line_no": 57, "clause_code": "A57", "clause_name": '部门责任和权限', "weight": 1, "max_score": 3, "remarks": 'RoHS/环保体系及维护'},
    {"line_no": 58, "clause_code": "A58", "clause_name": '是否建立有害物质控制标准包括：POPs、REACH-SVHC、REACH XVII、包装指令、电池指令、欧盟RoHS 10项等。', "weight": 1, "max_score": 3, "remarks": 'RoHS/环保体系及维护'},
    {"line_no": 59, "clause_code": "A59", "clause_name": '是否有渠道识别新法规及体系标准，并及时转换为内部管控标准', "weight": 1, "max_score": 3, "remarks": 'RoHS/环保体系及维护'},
    {"line_no": 60, "clause_code": "A60", "clause_name": '内部环保审核计划和实施情况', "weight": 1, "max_score": 3, "remarks": 'RoHS/环保体系及维护'},
    {"line_no": 61, "clause_code": "A61", "clause_name": '员工环保知识培训计划、实施及课件确认', "weight": 1, "max_score": 3, "remarks": 'RoHS/环保体系及维护'},
    {"line_no": 62, "clause_code": "A62", "clause_name": '环保供应商清单', "weight": 1, "max_score": 3, "remarks": 'RoHS/供应商管理'},
    {"line_no": 63, "clause_code": "A63", "clause_name": '上游供应商环保资料提供（限制物质声明、协议）', "weight": 1, "max_score": 3, "remarks": 'RoHS/供应商管理'},
    {"line_no": 64, "clause_code": "A64", "clause_name": '上游供应商有无提供材料清单？有无提供第三方报告提供并做有效期监控？', "weight": 1, "max_score": 3, "remarks": 'RoHS/供应商管理'},
    {"line_no": 65, "clause_code": "A65", "clause_name": '上游供应商所供材料的环保标识管理', "weight": 1, "max_score": 3, "remarks": 'RoHS/供应商管理'},
    {"line_no": 66, "clause_code": "A66", "clause_name": '上游供应商新增及4M变更时的风险预估及管控措施', "weight": 1, "max_score": 3, "remarks": 'RoHS/供应商管理'},
    {"line_no": 67, "clause_code": "A67", "clause_name": '上游供应商环保审核计划及实施情况，包括邻苯4P管控体系的审查', "weight": 1, "max_score": 3, "remarks": 'RoHS/供应商管理'},
    {"line_no": 68, "clause_code": "A68", "clause_name": '材料环保检查指导书及环保判定依据', "weight": 1, "max_score": 3, "remarks": 'RoHS/进检环保控制'},
    {"line_no": 69, "clause_code": "A69", "clause_name": 'RoHS六项、邻苯4P及卤素材料风险评估及风险等级管理', "weight": 1, "max_score": 3, "remarks": 'RoHS/进检环保控制'},
    {"line_no": 70, "clause_code": "A70", "clause_name": '环保检测设备，是否在计量合格有效期内？', "weight": 1, "max_score": 3, "remarks": 'RoHS/进检环保控制'},
    {"line_no": 71, "clause_code": "A71", "clause_name": '检测人员是否具备资质？', "weight": 1, "max_score": 3, "remarks": 'RoHS/进检环保控制'},
    {"line_no": 72, "clause_code": "A72", "clause_name": '检测仪器是否使用校准片进行有效校准？是否有制定操作指导书？', "weight": 1, "max_score": 3, "remarks": 'RoHS/进检环保控制'},
    {"line_no": 73, "clause_code": "A73", "clause_name": 'RoHS六项、邻苯4P和卤素抽检计划及实施情况，对抽检不合格品的处理是否符合不合格品处理流程', "weight": 1, "max_score": 3, "remarks": 'RoHS/进检环保控制'},
    {"line_no": 74, "clause_code": "A74", "clause_name": '抽检计划及实施情况，对抽检不合格品的处理是否符合不合格品处理流程', "weight": 1, "max_score": 3, "remarks": 'RoHS/进检环保控制'},
    {"line_no": 75, "clause_code": "A75", "clause_name": '产品是否全部切换为RoHS产品', "weight": 1, "max_score": 3, "remarks": 'RoHS/制程环保控制'},
    {"line_no": 76, "clause_code": "A76", "clause_name": '生产过程使用的辅料和工装夹具是否已全部进行过RoHS测试确认并防止混用？', "weight": 1, "max_score": 3, "remarks": 'RoHS/制程环保控制'},
    {"line_no": 77, "clause_code": "A77", "clause_name": '环保不合格的处理流程及记录', "weight": 1, "max_score": 3, "remarks": 'RoHS/制程环保控制'},
    {"line_no": 78, "clause_code": "A78", "clause_name": '材料和工艺变更的有害物质管理', "weight": 1, "max_score": 3, "remarks": 'RoHS/制程环保控制'},
    {"line_no": 79, "clause_code": "A79", "clause_name": '企业法人营业执照是否在有效期内？企业经营许可范围是否与实际经营业务相符？是否取得相应的许可证？（印刷、化学品类供应商适用）', "weight": 1, "max_score": 3, "remarks": '企业守法与供应链安全/企业守法与供应链安全'},
    {"line_no": 80, "clause_code": "A80", "clause_name": '企业经营及进出口活动是否遵守相关法律法规？', "weight": 1, "max_score": 3, "remarks": '企业守法与供应链安全/企业守法与供应链安全'},
    {"line_no": 81, "clause_code": "A81", "clause_name": '企业法定代表人（负责人）、进出口及财务高级管理人员守法及个人信用状况是否良好？', "weight": 1, "max_score": 3, "remarks": '企业守法与供应链安全/企业守法与供应链安全'},
    {"line_no": 82, "clause_code": "A82", "clause_name": '场所安全：是否建立企业经营场所安全的管理制度并有效落实。包括：工厂大门是否有保安驻守及设置围墙，以防止未载明货物和未经许可人员进入？是否在工厂出入口、货物装卸和储存区安装视频监控并保存60天以上？', "weight": 1, "max_score": 3, "remarks": '企业守法与供应链安全/企业守法与供应链安全'},
    {"line_no": 83, "clause_code": "A83", "clause_name": '进入安全：是否建立人员和车辆出入管理制度并有效落实。包括：是否对员工身份识别及出入权限控制？是否限制未经授权员工进入敏感区域？员工车辆进入是否停放在指定区域？是否实行访客登记管理及检查带有照片的身份证件？', "weight": 1, "max_score": 3, "remarks": '企业守法与供应链安全/企业守法与供应链安全'},
    {"line_no": 84, "clause_code": "A84", "clause_name": '货物安全：是否建立货物运输、装卸和存储安全管理制度并有效落实。包括：是否在货物关键交接环节有签名、盖章等保护措施？是否对出口货物实施专人监装并保存监装记录？是否制定进口货物溢、短装异常处理机制？', "weight": 1, "max_score": 3, "remarks": '企业守法与供应链安全/企业守法与供应链安全'},
    {"line_no": 85, "clause_code": "A85", "clause_name": '运输工具安全：建立保证运输工具的完整性、安全性的管理制度并有效落实。包括：是否对货物运输车辆进出进行检查？集装箱是否保存在安全区域？是否在货物装运和接收前对司机进行身份核实？', "weight": 1, "max_score": 3, "remarks": '企业守法与供应链安全/企业守法与供应链安全'},
    {"line_no": 86, "clause_code": "A86", "clause_name": '危机管理：是否建立应对灾害、紧急情况的应急预案。包括：火灾、台风暴雨等自然灾害或紧急情况？', "weight": 1, "max_score": 3, "remarks": '企业守法与供应链安全/企业守法与供应链安全'},
    {"line_no": 87, "clause_code": "A87", "clause_name": '安全培训：是否建立供应链安全的内部培训机制并有效落实。包括：是否定期对员工进行供应链安全和危险管理培训？是否定期对员工进行危机处理模拟演练？', "weight": 1, "max_score": 3, "remarks": '企业守法与供应链安全/企业守法与供应链安全'},
]

ELECTRONICS_SUPPLIER_EVAL_ANNUAL_ONSITE_CLAUSE_COUNT = len(ELECTRONICS_SUPPLIER_EVAL_ANNUAL_ONSITE_CLAUSES)
