"""L52 例试委托：类型、审核节点与待提交实验室状态常量。"""

from apps.kuaiplm.constants.lab_request_types import (
    LAB_REQUEST_AUDIT_NODE_BY_BUSINESS_TYPE,
    LAB_REQUEST_AUDIT_NODE_PROJECT_MATERIAL,
    LAB_REQUEST_AUDIT_NODE_PROJECT_PRODUCT,
    LAB_REQUEST_STATUS_AWAITING_LAB_DISPATCH,
    LAB_REQUEST_TYPE_PROJECT_MATERIAL,
    LAB_REQUEST_TYPE_PROJECT_PRODUCT,
    LAB_REQUEST_TYPES_REQUIRE_MANAGER_REVIEW,
    LAB_REQUEST_TYPES_USE_LAB_DISPATCH,
)
def test_l52_types_require_review_and_dispatch():
    assert LAB_REQUEST_TYPE_PROJECT_MATERIAL in LAB_REQUEST_TYPES_REQUIRE_MANAGER_REVIEW
    assert LAB_REQUEST_TYPE_PROJECT_PRODUCT in LAB_REQUEST_TYPES_REQUIRE_MANAGER_REVIEW
    assert LAB_REQUEST_TYPES_USE_LAB_DISPATCH == frozenset(
        {LAB_REQUEST_TYPE_PROJECT_MATERIAL, LAB_REQUEST_TYPE_PROJECT_PRODUCT}
    )


def test_l52_audit_nodes():
    assert (
        LAB_REQUEST_AUDIT_NODE_BY_BUSINESS_TYPE[LAB_REQUEST_TYPE_PROJECT_MATERIAL]
        == LAB_REQUEST_AUDIT_NODE_PROJECT_MATERIAL
    )
    assert (
        LAB_REQUEST_AUDIT_NODE_BY_BUSINESS_TYPE[LAB_REQUEST_TYPE_PROJECT_PRODUCT]
        == LAB_REQUEST_AUDIT_NODE_PROJECT_PRODUCT
    )
    assert (
        LAB_REQUEST_AUDIT_NODE_BY_BUSINESS_TYPE["project_product"]
        == LAB_REQUEST_AUDIT_NODE_PROJECT_PRODUCT
    )


def test_awaiting_lab_dispatch_status_value():
    assert LAB_REQUEST_STATUS_AWAITING_LAB_DISPATCH == "awaiting_lab_dispatch"
